function setModalHeaders() {
  const card1 = document.createElement("div");
  card1.classList.add("card", "spec-card-size");
  card1.id = "spec-card1";
  const card2 = document.createElement("div");
  card2.classList.add("card", "spec-card-size");
  card2.id = "spec-card2";
  const card3 = document.createElement("div");
  card3.classList.add("card", "spec-card-size");
  card3.id = "spec-card3";
  const card4 = document.createElement("div");
  card4.classList.add("card", "spec-card-size");
  card4.id = "spec-card4";
  const card5 = document.createElement("div");
  card5.classList.add("card", "spec-card-size");
  card5.id = "spec-card5";
  const card6 = document.createElement("div");
  card6.classList.add("card", "spec-card-size");
  card6.id = "spec-card6";
  const card7 = document.createElement("div");
  card7.classList.add("card", "spec-card-size");
  card7.id = "spec-card7";
  const card8 = document.createElement("div");
  card8.classList.add("card", "spec-card-size");
  card8.id = "spec-card8";
  const card9 = document.createElement("div");
  card9.classList.add("card", "spec-card-size");
  card9.id = "spec-card9";
  const card10 = document.createElement("div");
  card10.classList.add("card", "spec-card-size");
  card10.id = "spec-card10";
  const card11 = document.createElement("div");
  card11.classList.add("card", "spec-card-size");
  card11.id = "spec-card11";
  const card12 = document.createElement("div");
  card12.classList.add("card", "spec-card-size");
  card12.id = "spec-card12";
  const card13 = document.createElement("div");
  card13.classList.add("card", "spec-card-size");
  card13.id = "spec-card13";
  const processorHeader = document.createElement("div");
  processorHeader.classList.add("card-header", "spec-header-align");
  processorHeader.innerText = "Processor";
  const displayHeader = document.createElement("div");
  displayHeader.classList.add("card-header", "spec-header-align");
  displayHeader.innerText = "Display";
  const storageAndRamHeader = document.createElement("div");
  storageAndRamHeader.classList.add("card-header", "spec-header-align");
  storageAndRamHeader.innerText = "Storage and RAM";
  const cameraHeader = document.createElement("div");
  cameraHeader.classList.add("card-header", "spec-header-align");
  cameraHeader.innerText = "Camera";
  const audioHeader = document.createElement("div");
  audioHeader.classList.add("card-header", "spec-header-align");
  audioHeader.innerText = "Audio";
  const batteryAndChargingHeader = document.createElement("div");
  batteryAndChargingHeader.classList.add("card-header", "spec-header-align");
  batteryAndChargingHeader.innerText = "Battery & Charging";
  const cellularAndWirelessHeader = document.createElement("div");
  cellularAndWirelessHeader.classList.add("card-header", "spec-header-align");
  cellularAndWirelessHeader.innerText = "Cellular and Wireless";
  const sizeAndWeightHeader = document.createElement("div");
  sizeAndWeightHeader.classList.add("card-header", "spec-header-align");
  sizeAndWeightHeader.innerText = "Size & Weight";
  const materialHeader = document.createElement("div");
  materialHeader.classList.add("card-header", "spec-header-align");
  materialHeader.innerText = "Material";
  const sensorsHeader = document.createElement("div");
  sensorsHeader.classList.add("card-header", "spec-header-align");
  sensorsHeader.innerText = "Sensors";
  const operatingSystemHeader = document.createElement("div");
  operatingSystemHeader.classList.add("card-header", "spec-header-align");
  operatingSystemHeader.innerText = "Operating System";
  const colorsHeader = document.createElement("div");
  colorsHeader.classList.add("card-header", "spec-header-align");
  colorsHeader.innerText = "Colors";
  const priceHeader = document.createElement("div");
  priceHeader.classList.add("card-header", "spec-header-align");
  priceHeader.innerText = "Price";
  document.getElementById("spec-card1").appendChild(processorHeader);
  document.getElementById("spec-card2").appendChild(displayHeader);
  document.getElementById("spec-card3").appendChild(storageAndRamHeader);
  document.getElementById("spec-card4").appendChild(cameraHeader);
  document.getElementById("spec-card5").appendChild(audioHeader);
  document.getElementById("spec-card6").appendChild(batteryAndChargingHeader);
  document.getElementById("spec-card7").appendChild(cellularAndWirelessHeader);
  document.getElementById("spec-card8").appendChild(sizeAndWeightHeader);
  document.getElementById("spec-card9").appendChild(materialHeader);
  document.getElementById("spec-card10").appendChild(sensorsHeader);
  document.getElementById("spec-card11").appendChild(operatingSystemHeader);
  document.getElementById("spec-card12").appendChild(colorsHeader);
  document.getElementById("spec-card13").appendChild(priceHeader);
  // Append
  document.getElementsByClassName("phone-specs-header").appendChild(card1);
  document.getElementById("spec-container").appendChild(card2);
  document.getElementById("spec-container").appendChild(card3);
  document.getElementById("spec-container").appendChild(card4);
  document.getElementById("spec-container").appendChild(card5);
  document.getElementById("spec-container").appendChild(card6);
  document.getElementById("spec-container").appendChild(card7);
  document.getElementById("spec-container").appendChild(card8);
  document.getElementById("spec-container").appendChild(card9);
  document.getElementById("spec-container").appendChild(card10);
  document.getElementById("spec-container").appendChild(card11);
  document.getElementById("spec-container").appendChild(card12);
  document.getElementById("spec-container").appendChild(card13);
}

setModalHeaders();
